import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>X Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
				<h1>Your personal assistant</h1>
				<p>Connect to different channels, whatsapp, slack</p>
				<p>teach new acknowledgment to your assistant based in text, audio, video</p><br/>
				<div class="container">
					<p>Ingrese una oración</p>
					<textarea id="text" value="hola"></textarea> <br/><br/>
					<button onclick="handleSubmit()">Send</button>
					<div id="prediction"></div>
				</div>
      </main>
    </>
  )
}
