import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

	const [response, setResponse] = useState();

	const handleSubmit = async (e) => {
		e.preventDefault();
		const text = e.target.text.value;
		const res = await fetch('/api/davinci', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({ prompt: text }),
		});
		const data = await res.json();
		setResponse(data)
		console.log('data', data);
	}

  return (
    <>
      <Head>
        <title>X Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
				<h1>Your personal assistant</h1>
				<p>Connect to different channels, whatsapp, slack</p>
				<p>teach new acknowledgment to your assistant based in text, audio, video</p><br/>
				<p>{response}</p>
				<form onSubmit={handleSubmit}>
					<div className="upload-image">
						{/* <h3>Chat:</h3><br/> */}
						<input type="text" id="text" name="text"/><br/><br/>
						<button type="submit">Send</button>
					</div>
				</form>
      </main>
    </>
  )
}
