import styles from '@/styles/Posts.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import clientPromise from '../../lib/mongodb'

export async function getServerSideProps(context) {
	try {
		const client = await clientPromise
		const db = await client.db(process.env.MONGO_DB_NEWS);
		const collection = db.collection(process.env.MONGO_COLLECTION_HN);

		const todayZero = new Date();
		todayZero.setHours(0);
		todayZero.setMinutes(0);
		todayZero.setSeconds(0);
		const todayZeroTime = todayZero.getTime();

		const news = await collection.find({
			created_at: { $gt: todayZeroTime },
			"data.0.summary": { $exists: true }
		}).toArray()

		return {
			props: {
				isConnected: true,
				news: JSON.parse(JSON.stringify(news)),
			},
		}
	} catch (err) {
		console.error("server side err:", err);
    return {
      props: { isConnected: false },
    }
	}
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({
	isConnected,
	news,
}) {

	// console.log("isConnected: ", isConnected);
	// console.log("news: ", news[0]);

  return (
    <>
      <Head>
        <title>AI-Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
				<div className='content'>
					{news[0].data.map((item, index) => {
						// console.log('nes decomposition: ', index, item)
						return (
							<div key={index}>
								<h3>{index+1}. <a href={item.link}>{item.title}</a></h3>
								<ul>
									{item.summary.split('.,').map((sentence, index) => {
										return (
											<li key={index}>{sentence}</li>
										)
									})}
								</ul>
							</div>
						)
					})}
				</div>
      </main>
    </>
  )
}
