import styles from '@/styles/Posts.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import clientPromise from '../../lib/mongodb'

export async function getServerSideProps(context) {
	console.log('context', context);
	try {
		const client = await clientPromise
		const db = await client.db(process.env.MONGO_DB_NEWS);
		const collection = db.collection(process.env.MONGO_COLLECTION_HN);

		// TODO
		// Update time after 00:00
		// Show day before, if the summaries are not ready.
		// Potencially call function if are not ready.
		// or programaticlly call cronJob several times.
		// maybe the reason dind't work is the time, and in production wait 3m is not possible or some issue related.

		const todayZero = new Date();
		todayZero.setHours(1);
		todayZero.setMinutes(0);
		todayZero.setSeconds(0);
		const todayZeroTime = todayZero.getTime();

		console.log('vercel_url', process.env.VERCEL_URL);
		console.log('AUTH0_BASE_URL', process.env.AUTH0_BASE_URL);
		const baseUrl = process.env.AUTH0_BASE_URL


		let news = await collection.find({
			created_at: { $gt: todayZeroTime },
			"type": "summary"
		}).toArray()
		news = news[0];

		// TODO si news es undefindated, llamar a la serverless function scraped
		if(news === undefined) {
			let res = await fetch(`${baseUrl}/api/scrap`);
			res = await res.json();
			console.log('res', res);
		}

		return {
			props: {
				isConnected: true,
				news: JSON.parse(JSON.stringify(news)),
			},
		}
	} catch (err) {
		console.error("server side err:", err);
    return {
      props: { isConnected: false },
    }
	}
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({
	isConnected,
	news,
}) {

	const handleSubmit = async (e) => {
		e.preventDefault();
		const email = e.target.email.value;
		if (!email) return;
		try {
			const res = await fetch('/api/new-suscripter', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ email: email }),
			});
			const data = await res.json();
			if(data.success === 'Ok') {
				document.getElementById('status').style.color  = "green"
				document.getElementById('status').innerHTML = 'Subscription successful';
			} else {
				document.getElementById('status').style.color  = "red"
				document.getElementById('status').innerHTML = 'Error';
			}
		} catch (error) {
			console.log(error)
			document.getElementById('status').style.color  = "red"
			document.getElementById('status').innerHTML = 'Error';
		}
		e.target.email.value = '';
	}

  return (
    <>
      <Head>
        <title>AI-Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
				<div className={styles.suscription}>
					<form onSubmit={handleSubmit} className={styles.formClass}>
						<input className={styles.email} type="text" id="email" placeholder="example@email.com" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" />
						<button className={styles.suscribe} type="submit">suscribe</button>
						<div id='status'></div>
					</form>
				</div>
				{isConnected && news !== undefined ?
					<div className='content'>
						{news.summaries.map((item, index) => {
							return (
								<div key={index}>
									<h3>{index+1}. <a href={item.link}>{item.title}</a></h3>
									<ul>
										{item.summary.split('.,').map((sentence, index) => {
											return (
												<li key={index}>{sentence}</li>
											)
										})}
									</ul>
								</div>
							)
						})}
					</div>
					: <h1>Today&apos;s AI Posts (offline), please come back in some minutes</h1>
				}
      </main>
    </>
  )
}
