import styles from '@/styles/Home.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useState } from 'react'
import { useUser } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

	const [response, setResponse] = useState();
	const { user, error, isLoading } = useUser();

	const handleSubmit = async (e) => {
		e.preventDefault();
		const text = e.target.text.value;
		const res = await fetch('/api/yt-transcribe', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify({ link: text }),
		});
		console.log('res', res);
		const data = await res.json();
		console.log(data);
		setResponse(data.transcription);
	}

  return (
    <>
      <Head>
        <title>YT summarization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
				<h1>Transcribe a youtube video</h1>
				{user ?
					(<form onSubmit={handleSubmit}>
						<div className="upload-image">
							<input type="text" id="text" name="text"/>
							<button type="submit">Send</button>
						</div>
					</form>)
					: (
					<div>
						<input type="text" id="text" name="text"/>
						<Link href="/api/auth/login"><button>Send</button></Link>
					</div>
					)
				}
				{user ? (<Link href="/api/auth/logout">Logout</Link>) : null}
      </main>
    </>
  )
}
